service: c4drawless

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  environment:
    SCHEMA_TABLE: schema-table-${self:provider.stage}
    SCREENSHOT_TABLE: screenshot-table-${opt:stage, self:provider.stage}
    SCREENSHOT_BUCKET_NAME: ${self:service}-screenshot-bucket-${self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - s3:GetObject
        - s3:PutObject
      Resource: "*"

custom:
  functionsBasePath: functions
  bucketname: ${self:provider.environment.SCREENSHOT_BUCKET_NAME}

functions:
  about:
    handler: about/about.handle
  listSchema:
    handler: schema/list.handle
  createSchema:
    handler: schema/create.handle
  listScreenshot:
    handler: screenshot/list.handle
  createScreenshot:
    handler: screenshot/create.handler
    events:
      - s3:
          bucket: rocketnodeserverless
          event: s3:ObjectCreated:*
          rules:
            - prefix: screenshot/
            - suffix: .jpg
      - s3:
          bucket: rocketnodeserverless
          event: s3:ObjectCreated:*
          rules:
            - prefix: screenshot/
            - suffix: .png

resources:
  Resources:
    ScreenshotBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketname}
    SchemaDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.SCHEMA_TABLE}
        AttributeDefinitions:
          - AttributeName: schemaId
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: schemaId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
        - IndexName: userIdIndex
          KeySchema:
          - AttributeName: userId
            KeyType: HASH
          Projection:
            NonKeyAttributes:
            - userId
            ProjectionType: INCLUDE
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
    ScreenshotDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.SCREENSHOT_TABLE}
        AttributeDefinitions:
          - AttributeName: screenshotId
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: screenshotId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
        - IndexName: userIdIndex
          KeySchema:
          - AttributeName: userId
            KeyType: HASH
          Projection:
            NonKeyAttributes:
            - userId
            ProjectionType: INCLUDE
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1

plugins:
  - serverless-functions-base-path
